### ISSUE TITLE
A framework to build cross/multi-platform client application

### ISSUE THREAD

**Issue by alfa-ryano** [York-and-Maastricht-Data-Science-Group/vaultage#3]
Client applications are needed to interact with users' and installed on users' devices.  Is there any Java framework that can target multi/cross-platforms?
So we don't have to develop a client application for each platform: android, ios, windows, web, linux, mac, etc.

**Comment by alfonsodelavega** [comment]
Maybe this is something to care in a more advanced state of the framework.

I would vote for temporarily closing this and reopening it later, so that existing issues are the ones we are actively working on.
